/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@cuuats/webmapgl';
import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface SntApp {}
  interface SntAppAttributes extends StencilHTMLAttributes {}

  interface SntModeToggle {
    'label': string;
  }
  interface SntModeToggleAttributes extends StencilHTMLAttributes {
    'label'?: string;
  }

  interface SntToggleList {}
  interface SntToggleListAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SntApp': Components.SntApp;
    'SntModeToggle': Components.SntModeToggle;
    'SntToggleList': Components.SntToggleList;
  }

  interface StencilIntrinsicElements {
    'snt-app': Components.SntAppAttributes;
    'snt-mode-toggle': Components.SntModeToggleAttributes;
    'snt-toggle-list': Components.SntToggleListAttributes;
  }


  interface HTMLSntAppElement extends Components.SntApp, HTMLStencilElement {}
  var HTMLSntAppElement: {
    prototype: HTMLSntAppElement;
    new (): HTMLSntAppElement;
  };

  interface HTMLSntModeToggleElement extends Components.SntModeToggle, HTMLStencilElement {}
  var HTMLSntModeToggleElement: {
    prototype: HTMLSntModeToggleElement;
    new (): HTMLSntModeToggleElement;
  };

  interface HTMLSntToggleListElement extends Components.SntToggleList, HTMLStencilElement {}
  var HTMLSntToggleListElement: {
    prototype: HTMLSntToggleListElement;
    new (): HTMLSntToggleListElement;
  };

  interface HTMLElementTagNameMap {
    'snt-app': HTMLSntAppElement
    'snt-mode-toggle': HTMLSntModeToggleElement
    'snt-toggle-list': HTMLSntToggleListElement
  }

  interface ElementTagNameMap {
    'snt-app': HTMLSntAppElement;
    'snt-mode-toggle': HTMLSntModeToggleElement;
    'snt-toggle-list': HTMLSntToggleListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
