/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@cuuats/webmapgl';
import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface SntApp {}
  interface SntAppAttributes extends StencilHTMLAttributes {}

  interface SntToggle {
    'attribute': string;
    'icon': string;
    'label': string;
    'type': 'mode' | 'destination';
  }
  interface SntToggleAttributes extends StencilHTMLAttributes {
    'attribute'?: string;
    'icon'?: string;
    'label'?: string;
    'type'?: 'mode' | 'destination';
  }

  interface SntToggles {}
  interface SntTogglesAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SntApp': Components.SntApp;
    'SntToggle': Components.SntToggle;
    'SntToggles': Components.SntToggles;
  }

  interface StencilIntrinsicElements {
    'snt-app': Components.SntAppAttributes;
    'snt-toggle': Components.SntToggleAttributes;
    'snt-toggles': Components.SntTogglesAttributes;
  }


  interface HTMLSntAppElement extends Components.SntApp, HTMLStencilElement {}
  var HTMLSntAppElement: {
    prototype: HTMLSntAppElement;
    new (): HTMLSntAppElement;
  };

  interface HTMLSntToggleElement extends Components.SntToggle, HTMLStencilElement {}
  var HTMLSntToggleElement: {
    prototype: HTMLSntToggleElement;
    new (): HTMLSntToggleElement;
  };

  interface HTMLSntTogglesElement extends Components.SntToggles, HTMLStencilElement {}
  var HTMLSntTogglesElement: {
    prototype: HTMLSntTogglesElement;
    new (): HTMLSntTogglesElement;
  };

  interface HTMLElementTagNameMap {
    'snt-app': HTMLSntAppElement
    'snt-toggle': HTMLSntToggleElement
    'snt-toggles': HTMLSntTogglesElement
  }

  interface ElementTagNameMap {
    'snt-app': HTMLSntAppElement;
    'snt-toggle': HTMLSntToggleElement;
    'snt-toggles': HTMLSntTogglesElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
