/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import 'ionicons';
import '@ionic/core';
import '@cuuats/webmapgl';


export namespace Components {

  interface SntApp {}
  interface SntAppAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SntApp': Components.SntApp;
  }

  interface StencilIntrinsicElements {
    'snt-app': Components.SntAppAttributes;
  }


  interface HTMLSntAppElement extends Components.SntApp, HTMLStencilElement {}
  var HTMLSntAppElement: {
    prototype: HTMLSntAppElement;
    new (): HTMLSntAppElement;
  };

  interface HTMLElementTagNameMap {
    'snt-app': HTMLSntAppElement
  }

  interface ElementTagNameMap {
    'snt-app': HTMLSntAppElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
